// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WatchMovieInformation.Models;

namespace WatchMovieInformation.Migrations
{
    [DbContext(typeof(WatchListDbContext))]
    [Migration("20171020061816_IntitalMigration")]
    partial class IntitalMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WatchMovieInformation.Models.Generic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GenericName");

                    b.HasKey("Id");

                    b.ToTable("Generics");
                });

            modelBuilder.Entity("WatchMovieInformation.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LanguageName");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("WatchMovieInformation.Models.WatchList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("GenericId");

                    b.Property<int?>("LanguageId");

                    b.Property<string>("MovieName");

                    b.HasKey("Id");

                    b.HasIndex("GenericId");

                    b.HasIndex("LanguageId");

                    b.ToTable("WatchLists");
                });

            modelBuilder.Entity("WatchMovieInformation.Models.WatchList", b =>
                {
                    b.HasOne("WatchMovieInformation.Models.Generic", "Generic")
                        .WithMany()
                        .HasForeignKey("GenericId");

                    b.HasOne("WatchMovieInformation.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId");
                });
#pragma warning restore 612, 618
        }
    }
}
